version: '2.1'

services:

  users-service:
    container_name: users-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER

      
  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - '5100:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/TheCodingLand/OtApi-microservice/master/swagger.json
    depends_on:
      users-service:
        condition: service_started