version: '2.1'

services:

  ot-ws:
    container_name: ot-ws
    build: ./
    volumes:
      - '.:/usr/src/app'
    environment:
      - OT_WS_URL=http://otrcsl01.rcsl.lu/otws/v1.asmx
      - APP_SETTINGS=project.config.DevelopmentConfig
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
      
  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - '5100:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=http://192.168.1.22:5001/api/ot/events/schema
    depends_on:
      ot-ws:
        condition: service_started