version: '2.1'

services:

  users-service:
    container_name: users-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5002:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.ProdConfig
    command: gunicorn -b 0.0.0.0:5000 manage:app
      
  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - '5100:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=http://148.110.107.15:5002/service.json
    depends_on:
      users-service:
        condition: service_started