version: '2.1'

services:

  ot-ws:
    container_name: ot-ws
    build: ./
    volumes:
      - '.:/usr/src/app'
    environment:
      - OT_WS_URL=http://otrcsl01.rcsl.lu/otws/v1.asmx
      - APP_SETTINGS=project.config.ProdConfig
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    command: gunicorn -b 0.0.0.0:5000 manage:app
      
  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - '5100:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/TheCodingLand/OtApi-microservice/master/swagger.json
    depends_on:
      ot-ws:
        condition: service_started